### ISSUE TITLE
Error with --threads 1 - persisting

### ISSUE THREAD

**Issue by wm75** [institut-de-genomique/HAPO-G#34] opened 2023-10-10 13:26 UTC
Hi,

just found that #21 is still an issue in the latest version in the case that sequence names contained non-alphanumeric characters. The reason is that when creating a simple symbolic link to the input fasta, that file doesn't have the sanitized sequence names so you'll get sth like `[E::faidx_adjust_position] The sequence "Contig0" was not found` in `logs/hapog_chunks_1.e`.

**Comment by bistace** [comment] 2023-10-10 13:45
Hello,

thank you for the report, this is indeed a corner case that I did not catch. I will work on a fix and update you on this.

**Comment by bistace** [comment] 2023-10-11 07:12
I just merged some changes into master. If you are not using the conda version, could you please verify that in your particular use-case the issue is indeed fixed? If you are using the conda version, I will make a release so it can be integrated into bioconda instead.

**Comment by wm75** [comment] 2023-11-21 11:23
Thanks for the fix and sorry for my delayed reply here.
I just patched my existing conda environment with your changes and that fixes the issue for me :rocket: 

One somewhat irritating thing is that when I compare the behavior of running with --threads 1 vs --threads 2 now on a tiny genome and just a handful of reads, there are striking runtime differences between the two: while the run finishes instantaneously with --threads 2 (each individual step in the pipeline getting reported as taking 0 seconds), the single-threaded run takes reported 10 seconds  after "Launching Hapo-G on each chunk". Much more than you'd expect, in particular, because the --threads 2 version only creates a single chunk for my tiny test genome!
Final results are identical though.

Doesn't seem to have anything to do with the original issue here, but could hint at some issue further down the pipeline when running with a single thread?

**Comment by bistace** [comment] 2023-11-21 14:03
Hello and thank you for reporting! 

The wait time of 10 seconds is because the number of chunks can be superior to the number of threads so the wrapper script is waiting 10 seconds between each verification to see if it can launch more jobs. 10 seconds is maybe a bit too much, I will lower it and make a release!

**Closed as completed** 2023-11-21 14:05 UTC
